version: '3'

volumes:
  booking_booking_maria:
    external:
      name: booking_booking_maria

networks:
  booking_booking_service_network:
    name: booking_booking_service_network
    driver: bridge

services:
  booking_booking_maria:
    restart: on-failure
    image: 'mariadb:10.3'
    container_name: 'booking-maria-container'
    environment:
      MYSQL_DATABASE: booking_booking
      MYSQL_USER: booking  
      MYSQL_PASSWORD: booking123!!
      MYSQL_ROOT_PASSWORD: booking123!
      TZ: Asia/Seoul
    networks:
      - booking_booking_service_network
    volumes:
      - 'booking_booking_maria:/var/lib/mysql'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    expose:
    - "3306"

  booking_booking_server:
    restart: on-failure
    depends_on:
      - booking_booking_maria
    image: 'booking-image:latest'
    container_name: 'booking-container'
    environment:
      CONFIG_URL: 'http://k9c206.p.ssafy.io:8123/'
    ports:
      - '9003:9003'
    networks:
      - booking_booking_service_network
